// This file is automatically generated. Do not edit it directly.
/// <reference types="vite/client" />

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
// @ts-ignore
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Safety check — helps debug env loading problems
if (!SUPABASE_URL) {
  console.error("❌ Missing VITE_SUPABASE_URL. Check your .env file location.");
  throw new Error("Supabase URL is missing.");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ Missing VITE_SUPABASE_PUBLISHABLE_KEY. Check your .env file location.");
  throw new Error("Supabase key is missing.");
}

console.log("✅ Supabase envs loaded:");
console.log("VITE_SUPABASE_URL =", SUPABASE_URL);
console.log(
  "VITE_SUPABASE_PUBLISHABLE_KEY loaded?",
  !!SUPABASE_PUBLISHABLE_KEY
);

// Initialize Supabase client
export const supabase = createClient<any>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);